apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: omotes-influxdb
  name: omotes-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omotes-influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omotes-influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:1.7
          env:
            - name: INFLUXDB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: omotes-env-vars-secrets
                  key: INFLUXDB_ADMIN_USER
            - name: INFLUXDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omotes-env-vars-secrets
                  key: INFLUXDB_ADMIN_PASSWORD
            - name: INFLUXDB_PORT
              valueFrom:
                configMapKeyRef:
                  name: omotes-env-vars-cm
                  key: INFLUXDB_PORT
            - name: INFLUXDB_HTTP_BIND_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: omotes-env-vars-cm
                  key: INFLUXDB_PORT_BIND
            - name: INFLUXDB_BIND_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: omotes-env-vars-cm
                  key: INFLUXDB_RPC_PORT_BIND
            - name: INFLUXDB_DB
              value: omotes_timeseries
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: "true"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: omotes-env-vars-cm
                  key: LOG_LEVEL
          ports:
            - containerPort: {{ .Values.influxdb.port }}
              protocol: TCP
            - containerPort: {{ .Values.influxdb.rpcPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: omotes-influxdb-pvc
#          livenessProbe:
#            exec:
#              command:
#                - curl
#                - -sL
#                - -I
#                - localhost:$INFLUXDB_PORT/ping
#            periodSeconds: 10
#            timeoutSeconds: 5
      restartPolicy: Always
      volumes:
        - name: omotes-influxdb-pvc
          persistentVolumeClaim:
            claimName: omotes-influxdb-pvc
        - configMap:
            items:
              - key: influxdb-init.sh
                path: influxdb-init.sh
            name: omotes-influxdb-init-cm
            defaultMode: 0777
          name: omotes-influxdb-init-cm
