apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  annotations:
    use-subpath: "true"
  name: omotes-influxdb-init-cm
data:
  influxdb-init.sh: |
    {{- .Files.Get "influxdb-init.sh" | nindent 4 }}
