apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: omotes-influxdb
  name: omotes-influxdb
spec:
  ports:
    - name: {{ .Values.influxdb.port | quote }}
      port: {{ .Values.influxdb.port }}
      targetPort: {{ .Values.influxdb.port }}
    - name: {{ .Values.influxdb.rpcPort | quote }}
      port: {{ .Values.influxdb.rpcPort }}
      targetPort: {{ .Values.influxdb.rpcPort }}
  selector:
    app: omotes-influxdb
