apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  annotations:
    use-subpath: "true"
  name: omotes-postgres-init-cm
data:
  init.sql: |
    {{- .Files.Get "postgres-init.sql" | nindent 4 }}
