apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  annotations:
    use-subpath: "true"
  labels:
    app: omotes-rabbitmq
  name: omotes-rabbitmq-conf-cm
data:
  rabbitmq.conf: |
    {{- .Files.Get "rabbitmq.conf" | nindent 4 }}