apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  annotations:
    use-subpath: "true"
  name: omotes-rabbitmq-init-cm
data:
  rabbitmq-init.sh: |
    {{- .Files.Get "rabbitmq-init.sh" | nindent 4 }}
