{{ if .Values.omotesRest.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: omotes-rest
  name: omotes-rest
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    app: omotes-rest
{{ end }}
