{{ if .Values.omotesRest.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: omotes-rest
  name: omotes-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omotes-rest
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omotes-rest
    spec:
      initContainers:
        - name: rest-postgres-setup
          image: postgres:15.4
          env:
            - name: PG_DB
              value: omotes_rest
            - name: PG_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: omotes-env-vars-secrets
                  key: REST_POSTGRES_ROOT_USER
            - name: PG_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omotes-env-vars-secrets
                  key: REST_POSTGRES_ROOT_PASSWORD
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: omotes-env-vars-cm
                  key: LOG_LEVEL
            - name: PG_HOST
              value: omotes-rest-postgres
            - name: PG_PORT
              value: "5432"
            - name: PG_REST_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: omotes-env-vars-secrets
                  key: REST_POSTGRES_USER_NAME
            - name: PG_REST_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omotes-env-vars-secrets
                  key: REST_POSTGRES_USER_PASSWORD
          volumeMounts:
            - name: omotes-postgres-init-cm
              mountPath: /init.sql
              subPath: init.sql
          command: [ 'sh', '-c',
            '
            until pg_isready -h $PG_HOST -p $PG_PORT -d $PG_DB;
            do echo waiting for database; sleep 2; done;
            psql postgresql://$PG_ROOT_USER:$PG_ROOT_PASSWORD@$PG_HOST:$PG_PORT/$PG_DB -v PG_USERNAME=$PG_REST_USER_NAME -v PG_PASSWORD=$PG_REST_USER_PASSWORD -v PG_DB=$PG_DB -f /init.sql
            '
          ]
      containers:
        - env:
            - name: OMOTES_ID
              value: "omotes-rest"
            - name: RABBITMQ_HOSTNAME
              value: omotes-rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: omotes-env-vars-secrets
                  key: RABBITMQ_OMOTES_USER_NAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omotes-env-vars-secrets
                  key: RABBITMQ_OMOTES_USER_PASSWORD
            - name: RABBITMQ_VIRTUALHOST
              value: omotes
            - name: POSTGRES_HOST
              value: omotes-rest-postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: omotes_rest
            - name: POSTGRES_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: omotes-env-vars-secrets
                  key: REST_POSTGRES_ROOT_USER
            - name: POSTGRES_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omotes-env-vars-secrets
                  key: REST_POSTGRES_ROOT_PASSWORD
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: omotes-env-vars-secrets
                  key: REST_POSTGRES_USER_NAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omotes-env-vars-secrets
                  key: REST_POSTGRES_USER_PASSWORD
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: omotes-env-vars-cm
                  key: LOG_LEVEL
          image: {{ .Values.omotesRest.image }}:{{ .Values.omotesRest.version }}
          name: omotes-rest
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: init.sql
                path: init.sql
            name: omotes-postgres-init-cm
          name: omotes-postgres-init-cm
{{ end }}
