# Default values for omotes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgres:
  rootUserName: "root"
  rootUserPassword: "1234"
  devPort: "6432"
  orchestratorUserName: "omotes_orchestrator"
  orchestratorUserPassword: "somepass3"
  storage: "100Mi"

rabbitmq:
  port: "5672"
  rootUserName: "root"
  rootUserPassword: "5678"
  omotesUserName: "omotes"
  omotesUserPassword: "somepass1"
  celeryUserName: "celery"
  celeryUserPassword: "somepass2"
  storage: "100Mi"

influxdb:
  port: "8096"
  rpcPort: "8098"
  adminUserName: "root"
  adminUserPassword: "9012"
  writeUserName: "write1"
  writeUserPassword: "write9012"
  frontendAdminUserNAme: "front1"
  frontendAdminUserPassword: "front9012"
  storage: "100Mi"

orchestrator:
  image: "ghcr.io/project-omotes/omotes_orchestrator"
  version: "1.1.0"

workers:
  - name: "mesido-worker-optimizer"
    task_type: "grow_optimizer_default"
    image: "ghcr.io/project-omotes/omotes-grow-optimizer-worker"
    version: "2.0.3"
    number_of_replicas: 2
  - name: "mesido-worker-optimizer-with-pressure"
    task_type: "grow_optimizer_no_heat_losses"
    image: "ghcr.io/project-omotes/omotes-grow-optimizer-worker"
    version: "2.0.3"
    number_of_replicas: 2
  - name: "mesido-worker-optimizer-no-heat-losses"
    task_type: "grow_optimizer_with_pressure"
    image: "ghcr.io/project-omotes/omotes-grow-optimizer-worker"
    version: "2.0.3"
    number_of_replicas: 2
  - name: "mesido-worker-simulator"
    task_type: "grow_simulator"
    image: "ghcr.io/project-omotes/omotes-grow-optimizer-worker"
    version: "2.0.3"
    number_of_replicas: 2
  - name: "omotes-simulator-worker"
    task_type: "grow_optimizer_default"
    image: "ghcr.io/project-omotes/omotes-simulator-worker"
    version: "0.0.11"
    number_of_replicas: 2


# This can be set using `--set-file workflowsDefinitionJson=<config.json>` during helm install
workflowsDefinitionJson: |
  [
    {
      "workflow_type_name": "grow_optimizer_no_heat_losses",
      "workflow_type_description_name": "Draft Design - Quickscan Validation"
    }
  ]

omotesRest:
  enabled: True
  image: "ghcr.io/project-omotes/omotes_rest"
  version: "1.0.2"
  postgresStorage: "100Mi"
  postgresRootUserName: "root"
  postgresRootUserPassword: "1234"
  postgresUserName: "omotes_user"
  postgresUserPassword: "somepass3"

logLevel: "INFO"
